name: conversa-dev
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=conversa'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=dev'
    ports:
      - '5432:5432'
    networks:
      conversa-network-dev:
        aliases:
          - postgres

  appserver:
    build:
        context: .
        dockerfile: Dockerfile-dev
        args:
          - RUNTIME_DIR=/var/conversa/runtime
    depends_on:
        - postgres
    image: 'conversa:development'
    environment:
      - SPRING_CONFIG_NAME=application-dev
    networks:
      - conversa-network-dev

networks:
  conversa-network-dev:
    driver: bridge



