name: fluent-english
services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=fluent-english"
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_USER=root"
    ports:
      - "5432:5432"
    networks:
      fluent-english-network:
        aliases:
          - postgres

  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    ports:
      - "6379:6379"
    networks:
      fluent-english-network:
        aliases:
          - redis

  appserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RUNTIME_DIR=/var/fluent-english/runtime
    depends_on:
      - postgres
      - redis
    image: "fluent-english:latest"
    ports:
      - "8080:8080"
    networks:
      - fluent-english-network
networks:
  fluent-english-network:
    driver: bridge
    name: fluent-english-network
